"""
TerraSensus — AI Recommendations Service

All endpoints use the multi-model fallback chain (client.py):
  1. Vertex AI (Gemini Pro) — primary
  2. Claude Sonnet — fallback
  3. Rule-based local knowledge — always available

Every response includes the model source so the frontend can display
"Generated by Gemini" or "Guideline-based (AI temporarily unavailable)".

Endpoints:
  POST /onboarding/{plot_id}      Crop-aware soil education at plot registration
  POST /recommend/{plot_id}       Full soil recommendation (on-demand)
  POST /suppliers/{plot_id}       Eco-scored fertiliser supplier suggestions
  POST /regenerative/{plot_id}    Regenerative alternatives to synthetic inputs
"""

from pathlib import Path

from fastapi import FastAPI
from pydantic import BaseModel

from client import generate_with_fallback

app = FastAPI(title="TerraSensus AI Recommendations Service")
PROMPTS_DIR = Path(__file__).parent / "prompts"


# ── Models ────────────────────────────────────────────────────────────────────

class PlotContext(BaseModel):
    plot_id: str
    farmer_name: str
    region: str
    crop: str
    variety: str
    area_ha: float
    climate_zone: str
    farming_style: str
    moisture: float
    temperature: float
    ph: float
    nitrogen: float
    phosphorus: float
    potassium: float
    ec: float


class AIResult(BaseModel):
    plot_id: str
    model_source: str
    content: dict
    crop_thresholds: dict
    disclaimer: str = (
        "This recommendation is AI-generated guidance. "
        "For decisions affecting food security or significant financial investment, "
        "consult a qualified agronomist."
    )


# ── Helpers ───────────────────────────────────────────────────────────────────

def load_prompt(name: str, **kwargs) -> str:
    template = (PROMPTS_DIR / f"{name}.txt").read_text()
    return template.format(**kwargs) if kwargs else template


# ── Endpoints ─────────────────────────────────────────────────────────────────

@app.get("/health")
def health():
    return {"status": "ok", "service": "ai-recommendations"}


@app.post("/onboarding/{plot_id}", response_model=AIResult)
def plot_onboarding(plot_id: str, ctx: PlotContext):
    """
    Called when a farmer registers a new plot.
    Generates personalised soil education, watch list, and regional risk summary.
    Returns crop-aware thresholds so the mobile app shows correct healthy ranges.
    Uses fallback chain — always returns something even if all AI models are down.
    """
    from services.alert_engine.rules import get_thresholds

    crop_thresholds = get_thresholds(ctx.crop)
    context = ctx.model_dump()

    prompt = load_prompt("plot_onboarding", **context)
    result = generate_with_fallback(prompt, context, call_type="onboarding")

    return AIResult(
        plot_id=plot_id,
        model_source=result.source.value,
        content=result.content,
        crop_thresholds=crop_thresholds,
    )


@app.post("/recommend/{plot_id}", response_model=AIResult)
def recommend(plot_id: str, ctx: PlotContext):
    """Full soil health recommendation — on-demand from recommendations screen."""
    context = ctx.model_dump()
    from services.alert_engine.rules import get_thresholds

    prompt = load_prompt("soil_recommendation", **context)
    result = generate_with_fallback(prompt, context, call_type="recommend")

    return AIResult(
        plot_id=plot_id,
        model_source=result.source.value,
        content=result.content,
        crop_thresholds=get_thresholds(ctx.crop),
    )


@app.post("/suppliers/{plot_id}", response_model=AIResult)
def suppliers(plot_id: str, ctx: PlotContext):
    """Eco-scored fertiliser supplier recommendations."""
    context = ctx.model_dump()
    from services.alert_engine.rules import get_thresholds

    prompt = load_prompt("supplier_recommendation", **context)
    result = generate_with_fallback(prompt, context, call_type="supplier")

    return AIResult(
        plot_id=plot_id,
        model_source=result.source.value,
        content=result.content,
        crop_thresholds=get_thresholds(ctx.crop),
    )


@app.post("/regenerative/{plot_id}", response_model=AIResult)
def regenerative(plot_id: str, ctx: PlotContext):
    """Regenerative alternatives to synthetic fertilisers."""
    context = ctx.model_dump()
    from services.alert_engine.rules import get_thresholds

    prompt = load_prompt("regenerative_alternatives", **context)
    result = generate_with_fallback(prompt, context, call_type="regenerative")

    return AIResult(
        plot_id=plot_id,
        model_source=result.source.value,
        content=result.content,
        crop_thresholds=get_thresholds(ctx.crop),
    )
